"""add tier and tier_expired_at to user

Revision ID: dc2288c171ea
Revises: 
Create Date: 2026-01-09 11:12:24.359829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2288c171ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tier', sa.String(), nullable=True, server_default=sa.text("'free'")))
    op.add_column('user', sa.Column('tier_expires_at', sa.DateTime(timezone=True), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier_expires_at')
    op.drop_column('user', 'tier')
    # ### end Alembic commands ###
